<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RagSqlServer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Agents.AI" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\db\001-schema.sql" LogicalName="001-schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RagSqlServer.Tests" />
  </ItemGroup>

</Project>
